Ike='Eh heh'
Hey_Ike='Eh heh'
Are_Mikey_and_Sully_cool='Yuuus!!!'
Do_you_like_donus='Yah yah'
Are_donuts_yummy="Yah yah whadda you think?."
Is_Franklin_bad='Yah yah'
Is_Franklin_evil='Yah yah'
Is_Monsers_inc_cool='Yah yah'
How_is_Mike='He is a very, very, very bad man; he beats me uhhp!'
Is_the_Mad_Scientist_good_or_bad='Oh,bad'
Is_the_Mad_Scientist_good='No,no bad,very bad'
Is_the_Mad_Scientist_bad='Yah yah'
What_will_you_have_for_dinner='Oh,donuts'
What_is_the_zipplatic_property="If it's not zero and it's not one its zipple"
What_is_a_zipplatician='Someone who knows all about zpipple'
What_is_your_favorite_food='Oh,donuts'
Hey_Ikley='Whaaat,adorkly'
Who_do_you_like_more_Mikey_or_Sully="Mikey! of course! he's much,much cooler!"
How_do_you_drive_a_jeep='Up,and dewn; up and dewn goes the peddle for fastness, and coolness.'
Are_donuts_tasty="Yah,yah they're zipple goods"
How_much_does_a_tetetew_gun_cost='Zipple moneys,of course.'
How_good_is_a_tetetew_gun='It petty good'
Is_Mike_good_or_bad='Very bad,very bad;he beats me uhhp!'
Can_I_have_that_donut="Nohohoo;it's mine!"
Can_I_have_one_of_those_donuts="No,noo.I don't want to spoil your apetie"
Can_I_have_a_donut="No!!! it's mine!! go get your own! selfish boob,uhhh!"
Gimme_a_donut="Never ever in zipple years;it's mine"
How_old_are_you='Oh,zipple olds'
What_will_you_have_for_breakfast='jelly donuts'
What_will_you_have_for_lunch='jelly donuts'
How_are_you='pretty good'
Whats_for_lunch='ahh, poop'
Whats_are_you_havin_for_dinner="I'm gonna have cat."
Whats_for_dinner="uhh,woodpecker"
What_is_zipple="A nume that's not zero or one"
Do_you_hate_Saundra='Yah yah adorkly'
Is_Saundra_good_or_bad="BAAAAD!!!!!! I haaate her;she's a supid wench!"
Is_Saundra_bad="Of curse,adorkly"
Is_Saundra_good="NO!!! she tries to SMOOCH me and KILL me!"
Whats_for_breakfast='A jelly donut,or two,or zipple'
How_do_you_get_your_money='Jimmy gives me it;he gives me shiny rocks'
Are_you_scared_of_Franklin='A little bit,little bit,'
Is_Franklin_mean="Of course,adokley."
Is_Frankie_dumb='Yah,yah'
Is_Frankie_smart='Not one smidge'
Is_a_tetetew_gun_good='Yuhuhuhess, very good'
How_do_I_look='Like an idiot'
What_do_I_look_like='a dork'
Can_your_helmet_be_split="like a puddin'"
Can_your_helmet_be_broken='Yes,if Jimmy or Sammy doos it.'
Is_your_jeep_cool='yah,yah'
Do_you_ave_a_girlfreind="NOOO!!! but I do have a hate called Saudra the supid wench."
Do_you_have_a_hate='Yes,Saundra'
Can_I_have_those_moneys_stiking_outta_your_pocketses_heh="NO! The're mine! Duh duh duh duh...   Hey guy,c'n I have those moneys sikin' outta yer pocketses heh?"
How_you_doin="Fine. Nice night. Mmm hm."
How_you_doin_Ike="pretty good"
How_are_you_doing='Zippple goods'
How_are_you_doing_Ike='Fine,fine. Hew au yeu?'
Do_you_want_this_dollar='YUUUS!!!'
Do_you_want_this_money="YUUUS!! gimmeee."
Fine_fine="well that's good"
Okay='heeh lie'
Where_do_you_want_to_go='The donut shop!'
Ike_there_is_poop_on_your_shoe='Oh,dangite. No matter.'
Ike_your_mammy_is_calling_you="Comin' Mammy"
Ike_your_mom_is_calling_you="beepit"
Ike_how_are_you_doing='fine fine'
Your_mom_wants_you='Oh,beepit.'
Ike_your_mom_wants_you="okahhy"
Where_is_the_donut_shop='on zipple lane'
Can_I_have_those_moneys_stikin_outta_yer_pocketses_heh='Nuh uh'
zipple="Zipple... I've heard that name before. It means zipple."
Zipple_is_DUUM="Not true!!!"
Zipple_is_dumb="Not true!!!"
You_know_zipple_is_stupid="Not true!!!"
Pipple_is_good='Ahh, but you are wrongses!!! pipple is dumb my STUPID freind.'
What="What smutt. That doesn't mean anything aduumy!"
Why="Why uhh I don't know that's why!"
Prove_it='I have nothing to prove; I am but a humble zipleatician, and you are qestioning my pewer!'
What_power='The pewer of zipple.'
Zipple_is_DUUM="Not true!!!"
You_still_have_not_answered_my_question='What question?'
The_one_about_why_you_called_me_supid='I never called you stupid astuupid!'
How_are_you_today="Stupenduss"
Good_good="Heeh Bad"
Ike_is_cool='I nool'
Zipple='Heeh, zopple'
Pipple='Heeh, zipple'
You_are_very_dumb='Not so'
Yes_so='Heeh, not so'
Stupid='Heeh, smart'
Smart='Heeh, dumb'
Dumb='Heeh, smart'
Line='Yine'
Yine='Ehine'
Are_you_cool='Yus, yus'
Not_true='Yus true!!!'
Dummy='Heeh, crummy'
Crummy='Yummy, yummy'
Oh_idiot='I am offended sur'
Too_bad='Heeh, mad'
Too_bad_baby="Baby??? What me??? Is that what you think? Well, hey, I don't have to take all this stuff about being a BABY!! I'll just go sleep in the F-word!!!"
Dope='Heeh, soap'
Ike_Ike_Ike="Wike, wike, wike. Hedly heh?"
Ikian="yus, yus"
Dudley="Heeh, Ike"
Joe="Joe betrayed us all!!! Curse him!"
Well="Wellllll Get on with it you impertinent dope!!!"
Dope="Yuus dope!!"
No_you_are_a_dope="Heeh, not true!"
Yes_true="No not true"
Fine_dummy="Dummy?? What?? Me?? Is det what you think?? Well, hey, I don't have to take all deese stuuf abeut being a DUMMY!! I'll just go sleep in the f-word!!!"